### ISSUE TITLE
SEVERE error after success COCO converting

### ISSUE THREAD

**Issue by min20120907** [min20120907/Cell_RCNN_Qt#13]
```python  Traceback (most recent call last):
  File "F:\Mask_RCNN\samples\cell\cell_trainer.py", line 178, in zip2coco
    "region_attributes": {"name": dirname(dir).replace("-ROI", " ")+"-"+str(j)},

  File "F:\Programs\Anaconda3\lib\ntpath.py", line 221, in dirname
    return split(p)[0]
  File "F:\Programs\Anaconda3\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by min20120907** [comment]
Fixed by catching the exception
