### ISSUE TITLE
convert and quit the window

### ISSUE THREAD

**Issue by min20120907** [min20120907/Cell_RCNN_Qt#22]

**Comment by min20120907** [comment]
```python
Traceback (most recent call last):
  File "/mnt/2b619254-a77a-4bbc-9e10-052f1ff6a3cc/Cell_RCNN_Qt (copy)/batch_cocoShrinkThread.py", line 315, in run
    result.update(json.load(infile))
  File "/mnt/27ad1177-64ad-40f3-90a2-80da53492dfa/amaconda3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/mnt/27ad1177-64ad-40f3-90a2-80da53492dfa/amaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/mnt/27ad1177-64ad-40f3-90a2-80da53492dfa/amaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/mnt/27ad1177-64ad-40f3-90a2-80da53492dfa/amaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Aborted (core dumped)
```

**Comment by min20120907** [comment]
fixed by catching errors
